coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 10
        base: parent
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch:
      default:
        target: auto
        # Allows PRs without tests, overall stats count
        threshold: 100
        base: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null

comment: # enable code coverage comment on PR
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: true

ignore:
  - "versioneer.py"
  - "monai/_version.py"
