language: "en-US"
early_access: false
tone_instructions: "Be terse and to the point in all statements and commentary."
reviews:
  profile: chill
  high_level_summary: false
  # This placeholder doesn't exist, so this effectively disables the summary in the description.
  high_level_summary_placeholder: "@coderabbitai summary"
  sequence_diagrams: false
  auto_apply_labels: false
  suggested_reviewers: false
  changed_files_summary: false
  suggested_labels: false
  poem: false
  path_instructions:
    - path: '**/*.md'
      instructions: Remember that markdown documentation must be updated with the latest information.
  auto_review:
    # Automatic Review | Automatic code review
    enabled: true
    # Review draft PRs/MRs.
    drafts: false

knowledge_base:
  opt_out: true
