# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To build with a different base image
# please run `docker build` using the `--build-arg IMAGE=...` flag.
ARG IMAGE=debian:12-slim
FROM ${IMAGE} AS build

LABEL maintainer="monai.contact@gmail.com"

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt update && \
    apt upgrade -y && \
    apt install -y --no-install-recommends ca-certificates python3-pip python-is-python3 git && \
    apt clean && \
    rm -rf /usr/lib/python*/EXTERNALLY-MANAGED /var/lib/apt/lists/* 

WORKDIR /opt/monai

# copy relevant parts of repo
COPY requirements.txt requirements-min.txt requirements-dev.txt pyproject.toml versioneer.py setup.py setup.cfg ./
COPY LICENSE CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md README.md MANIFEST.in runtests.sh ./
COPY tests ./tests
COPY monai ./monai

RUN python -m pip install --upgrade --no-cache-dir pip && python -m pip install --no-cache-dir -r requirements-min.txt 

RUN BUILD_MONAI=0 FORCE_CUDA=1  python setup.py develop && rm -rf build __pycache__ 

# flatten all layers down to one
FROM ${IMAGE}
WORKDIR /opt/monai
COPY --from=build / /
