# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To build with a different base image
# please run `docker build` using the `--build-arg IMAGE=...` flag.
ARG IMAGE=debian:12-slim
FROM ${IMAGE} AS build

ENV DEBIAN_FRONTEND=noninteractive
ENV APT_INSTALL="apt install -y --no-install-recommends"

RUN apt update && apt upgrade -y && \
    ${APT_INSTALL} ca-certificates python3-pip python-is-python3 git wget libopenslide0 unzip python3-dev && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt update && \
    ${APT_INSTALL} cuda-toolkit-12 && \
    apt clean && \
    rm -rf cuda-keyring_1.1-1_all.deb /usr/lib/python*/EXTERNALLY-MANAGED /var/lib/apt/lists/*

# TODO: remark for issue [revise the dockerfile](https://github.com/zarr-developers/numcodecs/issues/431)
RUN if [[ $(uname -m) =~ "aarch64" ]]; then \
      CFLAGS="-O3" DISABLE_NUMCODECS_SSE2=true DISABLE_NUMCODECS_AVX2=true python -m pip install numcodecs; \
    fi

# NGC Client
WORKDIR /opt/tools
ARG NGC_CLI_URI="https://ngc.nvidia.com/downloads/ngccli_linux.zip"
RUN wget -q ${NGC_CLI_URI} && unzip ngccli_linux.zip && chmod u+x ngc-cli/ngc && \
    find ngc-cli/ -type f -exec md5sum {} + | LC_ALL=C sort | md5sum -c ngc-cli.md5 && \
    rm -rf ngccli_linux.zip ngc-cli.md5

WORKDIR /opt/monai

# copy relevant parts of repo
COPY requirements.txt requirements-min.txt requirements-dev.txt versioneer.py setup.py setup.cfg pyproject.toml ./
COPY LICENSE CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md README.md MANIFEST.in runtests.sh ./
COPY tests ./tests
COPY monai ./monai

# install full deps
RUN python -m pip install --upgrade --no-cache-dir pip && \
    python -m pip install --no-cache-dir -r requirements-dev.txt

RUN wget https://developer.download.nvidia.com/compute/cuda/repos/debian12/x86_64/cuda-keyring_1.1-1_all.deb && \
    dpkg -i cuda-keyring_1.1-1_all.deb && \
    apt update && \
    ${APT_INSTALL} cuda-toolkit-12

# compile ext and remove temp files
RUN export TORCH_CUDA_ARCH_LIST=Turing CUDA_HOME=/usr/local/cuda BUILD_MONAI=1 FORCE_CUDA=1 USE_COMPILED=1 && \
    python setup.py develop && \
    rm -rf build __pycache__ monai.egg-info

# flatten all layers down to one
FROM ${IMAGE}
LABEL maintainer="monai.contact@gmail.com"

WORKDIR /opt/monai
COPY --from=build / /

ENV PATH=${PATH}:/opt/tools:/opt/tools/ngc-cli
ENV POLYGRAPHY_AUTOINSTALL_DEPS=1
ENV CUDA_HOME=/usr/local/cuda
ENV BUILD_MONAI=1

# docker run -ti --rm --gpus '"device=0,1"' --shm-size=10gb monai_slim /bin/bash

# PYTHONPATH=. BUILD_MONAI=1 ./runtests.sh -u 2>&1|tee tests.log
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.networks.layers.filtering.test_trainable_bilateral
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.apps.detection.networks.test_retinanet.TestRetinaNet.test_onnx_0
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.integration.test_auto3dseg_hpo.TestHPO.test_run_algo
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.integration.test_auto3dseg_hpo.TestHPO.test_get_history
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.networks.layers.test_gmm
# python -m unittest tests.apps.vista3d.test_point_based_window_inferer
# python -m unittest tests.bundle.test_bundle_download.TestDownload.test_ngc_private_source_download_bundle_0
# python -m unittest tests.data.meta_tensor.test_meta_tensor.TestMetaTensor.test_pickling
# PYTHONPATH=. BUILD_MONAI=1 python -m unittest tests.networks.test_convert_to_onnx
