# daily tests for ngc bundles
name: cron-ngc-bundle

on:
  schedule:
    - cron: "0 2 * * *"  # at 02:00 UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # automatically cancel the previously triggered workflows when there's a newer version
  group: bundle-tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cron-load:
    if: github.repository == 'Project-MONAI/MONAI'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
        cache: pip
    - name: Install CPU PyTorch
      run: |
        python -m pip install torch==2.8.0 torchvision --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      run: |
        rm -rf /github/home/.cache/torch/hub/bundle/
        python -m pip install --no-build-isolation --upgrade pip wheel wheel-stub
        python -m pip install --no-build-isolation -r requirements-dev.txt
    - name: Loading Bundles
      run: |
        # clean up temporary files
        $(pwd)/runtests.sh --build --clean
        # run tests
        PYTHONPATH=. python -m unittest tests.bundle.test_bundle_download.TestNgcBundleDownload
